#lang racket

(require "boinc-xml.rkt")
(require "boinc-structs.rkt")
(require "xexpr-utils.rkt")
(require "parse.rkt")

(define (get-state)
           
  (let* ((state-xml (xexpr-get-document-element (get-state-xml)))
         (client-state (cddr (get-node (cddr state-xml) 'client_state)))
         (gse (lambda (x) (sublists-only (get-node client-state x))))
         (gses (lambda (x) (third (get-node client-state x))))
         (gns (lambda (x) (get-nodes client-state x))))
    (get-state-result (parse-host-info (gse 'host_info))
                      (parse-net-stats (gse 'net_stats))
                      (parse-time-stats (gse 'time_stats))
                      (parse-projects (gns 'project))
                      (parse-workunits (gns 'workunit)) 
                      (parse-results (gns 'result))     
                      (gses 'platform_name)
                      (gses 'core_client_major_version)
                      (gses 'core_client_minor_version)
                      (gses 'core_client_release)
                      (gses 'executing_as_daemon)
                      (gses 'platform) 
                      (parse-global-preferences (gse 'global_preferences))
                      (parse-app (gns 'app))
                      (parse-app-version (gns 'app_version)))))

(define (get-host-info)
    (parse-host-info (get-main-node get-host-info-xml 'host_info)))

(define (get-disk-usage)
  (let* ((disk-usage-node (get-main-node get-disk-usage-xml 'disk_usage_summary))
         (gs (lambda (x) (get-stat-value disk-usage-node x)))
         (gns (lambda (x) (get-nodes disk-usage-node x)))
         (f (lambda (x gs gse gns)
            (disk-usage-project (gs 'master_url)
                                (gs 'disk_usage)))))
    (disk-usage (gs 'd_total)
                (gs 'd_free)
                (gs 'd_boinc)
                (gs 'd_allowed)
                (accumulate-element-list (gns 'project) f))))

(define (get-cc-status)
  (let* ((cc-status-node (get-main-node get-cc-status-xml 'cc_status))
         (gs (lambda (x) (get-stat-value cc-status-node x))))
    (cc-status
     (gs 'network_status)
     (gs 'ams_password_error)
     (gs 'task_suspend_reason)
     (gs 'task_mode)
     (gs 'task_mode_perm)
     (gs 'task_mode_delay)
     (gs 'gpu_suspend_reason)
     (gs 'gpu_mode)
     (gs 'gpu_mode_perm)
     (gs 'gpu_mode_delay)
     (gs 'network_suspend_reason)
     (gs 'network_mode)
     (gs 'network_mode_perm)
     (gs 'network_mode_delay)
     (gs 'disallow_attach)
     (gs 'simple_gui_only)
     (gs 'max_event_log_lines))))

(define (get-project-status)
    (parse-projects (get-main-node get-project-status-xml 'projects)))
         
(define (get-results [active-only #f])
    (parse-results (get-main-node (lambda () (get-results-xml active-only)) 'results)))

(define (get-daily-transfer-history)

  (define (parse-daily-transfer-history nodes [output (list)])
    (if (empty? nodes)
        (list)
        (let* ((this-day (sublists-only (first nodes)))
               (gs (lambda (x) (get-stat-value this-day x)))               
               (dt (daily-transfer (gs 'when)
                                   (gs 'up)
                                   (gs 'down)))
               (new-output (append output (list dt))))
          
          (if (empty? (rest nodes))
              new-output
              (parse-daily-transfer-history (rest nodes) new-output)))))
          
  (let* ((root-xml (xexpr-get-document-element (get-daily-transfer-history-xml)))
         (main-node (sublists-only (get-node (cddr root-xml) 'daily_xfers)))
         (gns (lambda (x) (get-nodes main-node x))))
    (parse-daily-transfer-history (gns 'dx))))

